/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.2-dev */

#include "proto/proto.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(HeartbeatMsg, HeartbeatMsg, AUTO)


PB_BIND(StopMovingMsg, StopMovingMsg, AUTO)


PB_BIND(MovementEndedMsg, MovementEndedMsg, AUTO)


PB_BIND(EncoderPositionMsg, EncoderPositionMsg, AUTO)


PB_BIND(SetPIDMsg, SetPIDMsg, AUTO)


PB_BIND(SetMotionControlModeMsg, SetMotionControlModeMsg, AUTO)


PB_BIND(MoveWheelAtSpeedMsg, MoveWheelAtSpeedMsg, AUTO)


PB_BIND(TranslateMsg, TranslateMsg, AUTO)


PB_BIND(RotateMsg, RotateMsg, AUTO)


PB_BIND(BusMessage, BusMessage, AUTO)



