/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.2-dev */

#ifndef PB_PROTO_PROTO_PB_H_INCLUDED
#define PB_PROTO_PROTO_PB_H_INCLUDED
#include <COM/proto/pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _HeartbeatMsg {
    char dummy_field;
} HeartbeatMsg;

typedef struct _StopMovingMsg {
    char dummy_field;
} StopMovingMsg;

typedef struct _EncoderPositionMsg {
    int32_t left_tick;
    int32_t right_tick;
} EncoderPositionMsg;

typedef struct _MoveWheelAtSpeedMsg {
    int32_t left_tick_per_sec;
    int32_t right_tick_per_sec;
} MoveWheelAtSpeedMsg;

typedef struct _MovementEndedMsg {
    bool blocked;
} MovementEndedMsg;

typedef struct _RotateMsg {
    int32_t ticks;
} RotateMsg;

typedef struct _SetMotionControlModeMsg {
    bool speed;
    bool translation;
    bool rotation;
} SetMotionControlModeMsg;

typedef struct _SetPIDMsg {
    uint32_t pid_id;
    uint32_t translation_speed;
    uint32_t rotation_speed;
    uint32_t wheel_speed;
    uint32_t wheel_acceleration;
    uint32_t kp;
    uint32_t ki;
    uint32_t kd;
} SetPIDMsg;

typedef struct _TranslateMsg {
    int32_t ticks;
} TranslateMsg;

typedef struct _BusMessage {
    pb_size_t which_message;
    union {
        HeartbeatMsg heartbeat;
        StopMovingMsg stopMoving;
        MovementEndedMsg movementEnded;
        EncoderPositionMsg encoderPosition;
        SetPIDMsg setPID;
        SetMotionControlModeMsg setMotionControlMode;
        MoveWheelAtSpeedMsg moveWheelAtSpeed;
        TranslateMsg translate;
        RotateMsg rotate;
    } message;
} BusMessage;


/* Initializer values for message structs */
#define HeartbeatMsg_init_default                {0}
#define StopMovingMsg_init_default               {0}
#define MovementEndedMsg_init_default            {0}
#define EncoderPositionMsg_init_default          {0, 0}
#define SetPIDMsg_init_default                   {0, 0, 0, 0, 0, 0, 0, 0}
#define SetMotionControlModeMsg_init_default     {0, 0, 0}
#define MoveWheelAtSpeedMsg_init_default         {0, 0}
#define TranslateMsg_init_default                {0}
#define RotateMsg_init_default                   {0}
#define BusMessage_init_default                  {0, {HeartbeatMsg_init_default}}
#define HeartbeatMsg_init_zero                   {0}
#define StopMovingMsg_init_zero                  {0}
#define MovementEndedMsg_init_zero               {0}
#define EncoderPositionMsg_init_zero             {0, 0}
#define SetPIDMsg_init_zero                      {0, 0, 0, 0, 0, 0, 0, 0}
#define SetMotionControlModeMsg_init_zero        {0, 0, 0}
#define MoveWheelAtSpeedMsg_init_zero            {0, 0}
#define TranslateMsg_init_zero                   {0}
#define RotateMsg_init_zero                      {0}
#define BusMessage_init_zero                     {0, {HeartbeatMsg_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define EncoderPositionMsg_left_tick_tag         1
#define EncoderPositionMsg_right_tick_tag        2
#define MoveWheelAtSpeedMsg_left_tick_per_sec_tag 1
#define MoveWheelAtSpeedMsg_right_tick_per_sec_tag 2
#define MovementEndedMsg_blocked_tag             1
#define RotateMsg_ticks_tag                      1
#define SetMotionControlModeMsg_speed_tag        1
#define SetMotionControlModeMsg_translation_tag  2
#define SetMotionControlModeMsg_rotation_tag     3
#define SetPIDMsg_pid_id_tag                     1
#define SetPIDMsg_translation_speed_tag          2
#define SetPIDMsg_rotation_speed_tag             3
#define SetPIDMsg_wheel_speed_tag                4
#define SetPIDMsg_wheel_acceleration_tag         5
#define SetPIDMsg_kp_tag                         6
#define SetPIDMsg_ki_tag                         7
#define SetPIDMsg_kd_tag                         8
#define TranslateMsg_ticks_tag                   1
#define BusMessage_heartbeat_tag                 1
#define BusMessage_stopMoving_tag                2
#define BusMessage_movementEnded_tag             3
#define BusMessage_encoderPosition_tag           4
#define BusMessage_setPID_tag                    5
#define BusMessage_setMotionControlMode_tag      6
#define BusMessage_moveWheelAtSpeed_tag          7
#define BusMessage_translate_tag                 8
#define BusMessage_rotate_tag                    9

/* Struct field encoding specification for nanopb */
#define HeartbeatMsg_FIELDLIST(X, a) \

#define HeartbeatMsg_CALLBACK NULL
#define HeartbeatMsg_DEFAULT NULL

#define StopMovingMsg_FIELDLIST(X, a) \

#define StopMovingMsg_CALLBACK NULL
#define StopMovingMsg_DEFAULT NULL

#define MovementEndedMsg_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     blocked,           1)
#define MovementEndedMsg_CALLBACK NULL
#define MovementEndedMsg_DEFAULT NULL

#define EncoderPositionMsg_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, SINT32,   left_tick,         1) \
X(a, STATIC,   SINGULAR, SINT32,   right_tick,        2)
#define EncoderPositionMsg_CALLBACK NULL
#define EncoderPositionMsg_DEFAULT NULL

#define SetPIDMsg_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   pid_id,            1) \
X(a, STATIC,   SINGULAR, UINT32,   translation_speed,   2) \
X(a, STATIC,   SINGULAR, UINT32,   rotation_speed,    3) \
X(a, STATIC,   SINGULAR, UINT32,   wheel_speed,       4) \
X(a, STATIC,   SINGULAR, UINT32,   wheel_acceleration,   5) \
X(a, STATIC,   SINGULAR, UINT32,   kp,                6) \
X(a, STATIC,   SINGULAR, UINT32,   ki,                7) \
X(a, STATIC,   SINGULAR, UINT32,   kd,                8)
#define SetPIDMsg_CALLBACK NULL
#define SetPIDMsg_DEFAULT NULL

#define SetMotionControlModeMsg_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     speed,             1) \
X(a, STATIC,   SINGULAR, BOOL,     translation,       2) \
X(a, STATIC,   SINGULAR, BOOL,     rotation,          3)
#define SetMotionControlModeMsg_CALLBACK NULL
#define SetMotionControlModeMsg_DEFAULT NULL

#define MoveWheelAtSpeedMsg_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, SINT32,   left_tick_per_sec,   1) \
X(a, STATIC,   SINGULAR, SINT32,   right_tick_per_sec,   2)
#define MoveWheelAtSpeedMsg_CALLBACK NULL
#define MoveWheelAtSpeedMsg_DEFAULT NULL

#define TranslateMsg_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, SINT32,   ticks,             1)
#define TranslateMsg_CALLBACK NULL
#define TranslateMsg_DEFAULT NULL

#define RotateMsg_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, SINT32,   ticks,             1)
#define RotateMsg_CALLBACK NULL
#define RotateMsg_DEFAULT NULL

#define BusMessage_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,heartbeat,message.heartbeat),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,stopMoving,message.stopMoving),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,movementEnded,message.movementEnded),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,encoderPosition,message.encoderPosition),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,setPID,message.setPID),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,setMotionControlMode,message.setMotionControlMode),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,moveWheelAtSpeed,message.moveWheelAtSpeed),   7) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,translate,message.translate),   8) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,rotate,message.rotate),   9)
#define BusMessage_CALLBACK NULL
#define BusMessage_DEFAULT NULL
#define BusMessage_message_heartbeat_MSGTYPE HeartbeatMsg
#define BusMessage_message_stopMoving_MSGTYPE StopMovingMsg
#define BusMessage_message_movementEnded_MSGTYPE MovementEndedMsg
#define BusMessage_message_encoderPosition_MSGTYPE EncoderPositionMsg
#define BusMessage_message_setPID_MSGTYPE SetPIDMsg
#define BusMessage_message_setMotionControlMode_MSGTYPE SetMotionControlModeMsg
#define BusMessage_message_moveWheelAtSpeed_MSGTYPE MoveWheelAtSpeedMsg
#define BusMessage_message_translate_MSGTYPE TranslateMsg
#define BusMessage_message_rotate_MSGTYPE RotateMsg

extern const pb_msgdesc_t HeartbeatMsg_msg;
extern const pb_msgdesc_t StopMovingMsg_msg;
extern const pb_msgdesc_t MovementEndedMsg_msg;
extern const pb_msgdesc_t EncoderPositionMsg_msg;
extern const pb_msgdesc_t SetPIDMsg_msg;
extern const pb_msgdesc_t SetMotionControlModeMsg_msg;
extern const pb_msgdesc_t MoveWheelAtSpeedMsg_msg;
extern const pb_msgdesc_t TranslateMsg_msg;
extern const pb_msgdesc_t RotateMsg_msg;
extern const pb_msgdesc_t BusMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define HeartbeatMsg_fields &HeartbeatMsg_msg
#define StopMovingMsg_fields &StopMovingMsg_msg
#define MovementEndedMsg_fields &MovementEndedMsg_msg
#define EncoderPositionMsg_fields &EncoderPositionMsg_msg
#define SetPIDMsg_fields &SetPIDMsg_msg
#define SetMotionControlModeMsg_fields &SetMotionControlModeMsg_msg
#define MoveWheelAtSpeedMsg_fields &MoveWheelAtSpeedMsg_msg
#define TranslateMsg_fields &TranslateMsg_msg
#define RotateMsg_fields &RotateMsg_msg
#define BusMessage_fields &BusMessage_msg

/* Maximum encoded size of messages (where known) */
#define HeartbeatMsg_size                        0
#define StopMovingMsg_size                       0
#define MovementEndedMsg_size                    2
#define EncoderPositionMsg_size                  12
#define SetPIDMsg_size                           48
#define SetMotionControlModeMsg_size             6
#define MoveWheelAtSpeedMsg_size                 12
#define TranslateMsg_size                        6
#define RotateMsg_size                           6
#define BusMessage_size                          50

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
